
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Majus
 */
public class CrearUsuarioA extends javax.swing.JFrame {
    int x = 0; 
    Usuario us[];
    /**
     * Creates new form CrearUsuarioA
     */
    public CrearUsuarioA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idT = new javax.swing.JTextField();
        nombreT = new javax.swing.JTextField();
        apellidoT = new javax.swing.JTextField();
        userT = new javax.swing.JTextField();
        rolT = new javax.swing.JTextField();
        passUsuC = new javax.swing.JPasswordField();
        passUsuCC = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        passwordShow = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Crear Usuario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 180, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 60, 17, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 100, 60, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 140, 50, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("User:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 180, 50, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Rol:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 220, 22, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Contrraseña:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 260, 80, 14);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Confirmar Contraseña:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 260, 130, 14);

        idT.setPreferredSize(new java.awt.Dimension(28, 200));
        jPanel1.add(idT);
        idT.setBounds(230, 60, 200, 28);

        nombreT.setPreferredSize(new java.awt.Dimension(28, 200));
        jPanel1.add(nombreT);
        nombreT.setBounds(230, 100, 200, 28);

        apellidoT.setPreferredSize(new java.awt.Dimension(28, 200));
        apellidoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTActionPerformed(evt);
            }
        });
        jPanel1.add(apellidoT);
        apellidoT.setBounds(230, 140, 200, 28);

        userT.setPreferredSize(new java.awt.Dimension(28, 200));
        userT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTActionPerformed(evt);
            }
        });
        jPanel1.add(userT);
        userT.setBounds(230, 180, 200, 28);

        rolT.setPreferredSize(new java.awt.Dimension(28, 200));
        jPanel1.add(rolT);
        rolT.setBounds(230, 220, 200, 28);

        passUsuC.setPreferredSize(null);
        jPanel1.add(passUsuC);
        passUsuC.setBounds(120, 290, 150, 28);

        passUsuCC.setPreferredSize(null);
        jPanel1.add(passUsuCC);
        passUsuCC.setBounds(310, 290, 150, 28);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 350, 90, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(340, 350, 90, 30);

        passwordShow.setText("Mostrar contraseña");
        passwordShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordShowActionPerformed(evt);
            }
        });
        jPanel1.add(passwordShow);
        passwordShow.setBounds(120, 320, 130, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuariadmin.jpg"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 200));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 630, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apellidoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTActionPerformed

    private void userTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTActionPerformed

    private void passwordShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordShowActionPerformed
        // TODO add your handling code here:
        if(passwordShow.isSelected() ){
            passUsuC.setEchoChar((char)0);
            passUsuCC.setEchoChar((char)0);
        }else{
            passUsuC.setEchoChar('*');
            passUsuCC.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordShowActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(String.valueOf(passUsuC.getPassword()).equals(String.valueOf(passUsuCC.getPassword()))){
           
           us = new Usuario[x+1];
           // Asignando los valores que el usuario ingrese al crear el objeto.
           us[x] = new Usuario(idT.getText(), nombreT.getText(), apellidoT.getText(),userT.getText(), rolT.getText(), String.valueOf(passUsuC.getPassword()));
           
           x = x + 1;
           
           System.out.println("valor de x: " + x);
           System.out.println("id: " + us[x-1].getId() );
            
        }else{
            JOptionPane.showMessageDialog(this, "Contraseñas no coinciden!!!","Error Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        System.out.println(us[x-1].toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuarioA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoT;
    private javax.swing.JTextField idT;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreT;
    private javax.swing.JPasswordField passUsuC;
    private javax.swing.JPasswordField passUsuCC;
    private javax.swing.JCheckBox passwordShow;
    private javax.swing.JTextField rolT;
    private javax.swing.JTextField userT;
    // End of variables declaration//GEN-END:variables
}
