
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Majus
 */
public class ModificarBibliografias extends javax.swing.JFrame {

    usuarioAdmin modificarB;
    private String[] opciones = {"Libro","Revista","Tesis"};
    
    /**
     * Creates new form ModificarBibliografias
     */
    public ModificarBibliografias() {
        initComponents();
        
        this.setTitle("Modificar Bibliografias");
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        
        // Opciones de combo box
        for (String opcion : opciones) {
            this.jComboBox1.addItem(opcion);
        }
        // Selecionar libro al principio.
        jComboBox1.setSelectedIndex(0);
    }
    
    public ModificarBibliografias(usuarioAdmin modificarB) {
        initComponents();
        
        this.setTitle("Modificar Bibliografias");
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        
        this.modificarB = modificarB;
        
        // Opciones de combo box
        for (String opcion : opciones) {
            this.jComboBox1.addItem(opcion);
        }
        // Selecionar libro al principio.
        jComboBox1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar Bibliogarafia");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 370, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 60, 30, 14);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(70, 60, 160, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Autor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 90, 50, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 110, 200, 25);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Titulo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 140, 35, 14);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 160, 200, 25);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripcion:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 190, 70, 14);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 210, 200, 25);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Palabras Clave:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 240, 80, 14);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 260, 200, 25);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Edicion:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 290, 60, 14);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(30, 310, 200, 25);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 350, 80, 30);

        jButton2.setText("Cancel");
        jPanel1.add(jButton2);
        jButton2.setBounds(410, 350, 80, 30);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(360, 310, 200, 25);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(360, 260, 200, 25);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Disponibles:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(360, 290, 70, 14);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Copias:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(360, 240, 37, 14);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(360, 210, 200, 25);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Area:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(360, 190, 26, 14);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(360, 160, 200, 25);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ejemplares:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 140, 70, 14);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(360, 110, 200, 25);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Frecuencia Actual: ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 90, 150, 14);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(360, 60, 200, 25);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Temas:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(360, 40, 35, 14);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(520, 10, 73, 23);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(250, 60, 80, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if(evt.getSource() == jComboBox1){
            JComboBox cb = (JComboBox)evt.getSource();
            String msg = (String)cb.getSelectedItem();

            switch(msg){
                case "Libro" :
                jTextField7.setEditable(false);
                jTextField7.setBackground(Color.black);
                jTextField7.setForeground(Color.white);
                jTextField7.setText("No Aplica");

                jTextField8.setEditable(false);
                jTextField8.setBackground(Color.black);
                jTextField8.setForeground(Color.white);
                jTextField8.setText("No Aplica");

                jTextField9.setEditable(false);
                jTextField9.setBackground(Color.black);
                jTextField9.setForeground(Color.white);
                jTextField9.setText("No Aplica");

                break;
                case "Revista":
                jTextField7.setEditable(true);
                jTextField7.setBackground(jTextField1.getBackground());
                jTextField7.setForeground(jTextField1.getForeground());
                jTextField7.setText("");

                jTextField8.setEditable(true);
                jTextField8.setBackground(jTextField1.getBackground());
                jTextField8.setForeground(jTextField1.getForeground());
                jTextField8.setText("");

                jTextField9.setEditable(false);
                jTextField9.setBackground(Color.black);
                jTextField9.setForeground(Color.white);
                jTextField9.setText("No Aplica");
                break;
                case "Tesis":
                jTextField7.setEditable(false);
                jTextField7.setBackground(Color.black);
                jTextField7.setForeground(Color.white);
                jTextField7.setText("No Aplica");

                jTextField8.setEditable(false);
                jTextField8.setBackground(Color.black);
                jTextField8.setForeground(Color.white);
                jTextField8.setText("No Aplica");

                jTextField9.setEditable(true);
                jTextField9.setBackground(jTextField1.getBackground());
                jTextField9.setForeground(jTextField1.getForeground());
                jTextField9.setText("");
                break;
                default:System.out.println("Hay un puto error");

            }

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Verificar que objecto crear y agregar la informacion.

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        modificarB.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        boolean existe = false;
        String msg = (String) jComboBox1.getSelectedItem();
        switch (msg) {
            case "Libro":
                try {
                    for (int i = 0; i < Proyecto1.countL; i++) {
                        if (Proyecto1.biblioL[i].getAutor().equals(jTextField1.getText()) && Proyecto1.biblioL[i].getTitulo().equals(jTextField2.getText())) {
                            jTextField3.setText(Proyecto1.biblioL[i].getDescripcion());
                            jTextField4.setText(String.valueOf(Proyecto1.biblioL[i].getPalabraClave()));
                            jTextField5.setText(String.valueOf(Proyecto1.biblioL[i].getEdicion())); // EDICION
                            jTextField6.setText(String.valueOf(Proyecto1.biblioL[i].getTemas())); // TEMAS
                            jTextField10.setText(String.valueOf(Proyecto1.biblioL[i].getTemas()));//COPIAS
                            jTextField11.setText(String.valueOf(Proyecto1.biblioL[i].getDisponibles())); //DISPONIBLe
                            existe = true;
                        }
                    }
                } catch (Exception e) {
                }
                break;
            case "Revista":

                try {
                    for (int i = 0; i < Proyecto1.countR; i++) {
                        if (Proyecto1.biblioR[i].getAutor().equals(jTextField1.getText()) && Proyecto1.biblioR[i].getTitulo().equals(jTextField2.getText())) {
                            jTextField3.setText(Proyecto1.biblioR[i].getDescripcion());
                            jTextField4.setText(String.valueOf(Proyecto1.biblioR[i].getPalabraClave()));
                            jTextField5.setText(String.valueOf(Proyecto1.biblioR[i].getEdicion())); // EDICION
                            jTextField6.setText(String.valueOf(Proyecto1.biblioR[i].getTemas())); // TEMAS
                            jTextField10.setText(String.valueOf(Proyecto1.biblioR[i].getTemas()));//COPIAS
                            jTextField11.setText(String.valueOf(Proyecto1.biblioR[i].getDisponibles())); //DISPONIBLe
                            //Revista 7 y 8
                            jTextField7.setText(String.valueOf(Proyecto1.biblioR[i].getFrecuenciaActual()));
                            jTextField8.setText(String.valueOf(Proyecto1.biblioR[i].getEjemplares()));
                            existe = true;
                        }
                    }
                } catch (Exception e) {
                }
                break;
            case "Tesis":
                try {
                    for (int i = 0; i < Proyecto1.countT; i++) {
                        if (Proyecto1.biblioT[i].getAutor().equals(jTextField1.getText()) && Proyecto1.biblioT[i].getTitulo().equals(jTextField2.getText())) {
                            jTextField3.setText(Proyecto1.biblioT[i].getDescripcion());
                            jTextField4.setText(String.valueOf(Proyecto1.biblioT[i].getPalabraClave()));
                            jTextField5.setText(String.valueOf(Proyecto1.biblioT[i].getEdicion())); // EDICION
                            jTextField6.setText(String.valueOf(Proyecto1.biblioT[i].getTemas())); // TEMAS
                            jTextField10.setText(String.valueOf(Proyecto1.biblioT[i].getTemas()));//COPIAS
                            jTextField11.setText(String.valueOf(Proyecto1.biblioT[i].getDisponibles())); //DISPONIBLe
                            //Tesis 
                            jTextField9.setText(String.valueOf(Proyecto1.biblioT[i].getArea()));
                            existe = true;
                        }
                    }
                } catch (Exception e) {
                }

                break;
            default:
                System.out.println("SHO");
                break;
        }

        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese autor y titulo", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            existe = true;
        }

        if (!existe) {
            JOptionPane.showMessageDialog(this, "No existe", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarBibliografias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarBibliografias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarBibliografias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarBibliografias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarBibliografias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
